development:
  adapter: postgresql
  database: solidarity_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: solidarity_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: solidarity_production
  pool: 5
  timeout: 5000
